version: '3.8'
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
  #    depends_on:
  #      frontend:
  #        condition: service_healthy

  frontend:
    image: frontend-next
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "9000:9000"
    env_file:
      - .env
