import http from "k6/http";
import { check, sleep } from "k6";
import exec from "k6/execution";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export const options = {
    insecureSkipTLSVerify: true,
    stages:[
        // { duration: '30s', target: 20 },
        // { duration: '2m',  target: 20 },
        // { duration: '30s', target: 0 },
        { duration: '1s', target: 20 },
        { duration: '10s',  target: 20 },
        { duration: '1s', target: 0 },
    ],
    thresholds: {
        http_req_duration:['p(95)<500'],
        http_req_failed:['rate<0.01'],
    },
};

const BASE_URL    = 'https://larplaner-loadtest.onrender.com/api';
// const BASE_URL    = 'https://localhost:8443/api';
const ADMIN_TOKEN = 'admin-setup';
const USER_COUNT  = 20;

const adminHeaders = { 
    'Authorization': `Bearer ${ADMIN_TOKEN}`, 
    'Content-Type': 'application/json' 
};

function generateScenarioTemplate(userCount) {
    let roles =[];
    for (let i = 1; i <= userCount; i++) {
        roles.push({
            roleId: `{{roleId_Player${i}}}`,
            descriptionForGM: `Load Test Player ${i}`,
            descriptionForOwner: `You are Player ${i}.`,
            descriptionForOthers: `Player ${i} is ready.`
        });
    }

    return {
        name: `Load Test Scenario - ${userCount} Players`,
        description: "Auto-generated by K6 for Load Testing",
        roles: roles,
        items:[{
            name: "Central Loadtest Terminal",
            description: "A terminal designed to handle multiple concurrent interactions.",
            actions:[{
                name: "Ping Terminal",
                description: "A highly repeatable action.",
                messageOnSuccess: "Ping successful. Systems nominal.",
                messageOnFailure: "The terminal did not respond to the ping.",
                requiredTagsToDisplay: [], requiredTagsToSucceed:[],
                forbiddenTagsToDisplay:[], forbiddenTagsToSucceed:[],
                tagsToApplyOnSuccess:[], tagsToApplyOnFailure:[],
                tagsToRemoveOnSuccess:[], tagsToRemoveOnFailure:[]
            }]
        }],
        actions:[{
            name: "Scan the Room",
            description: "Look around at the other players.",
            messageOnSuccess: "You see the room is full of activity.",
            messageOnFailure: "The room is too dark to see anything.",
            requiredTagsToDisplay: [], requiredTagsToSucceed:[],
            forbiddenTagsToDisplay:[], forbiddenTagsToSucceed: [],
            tagsToApplyOnSuccess:[], tagsToApplyOnFailure:[],
            tagsToRemoveOnSuccess: [], tagsToRemoveOnFailure:[]
        }]
    };
}

export function setup() {
    console.log("--- Starting Setup Phase ---");

    // 1. Generate a single unique suffix for this setup run to avoid collisions
    // Uses current time + a random alphanumeric string (e.g., "lq4f9x-3ab")
    const runSuffix = Date.now().toString(36) + "-" + Math.random().toString(36).substring(2, 6);

    let scenarioObj = generateScenarioTemplate(USER_COUNT);
    let scenarioStr = JSON.stringify(scenarioObj);

    // 2. Extract Placeholders
    let matches = scenarioStr.match(/\{\{([^}]+)\}\}/g) || [];
    let uniquePlaceholders =[...new Set(matches)];
    let identifiers = uniquePlaceholders.map(p => p.replace('{{', '').replace('}}', ''));

    // 3. Create Tags in Bulk (with globally unique values)
    console.log(`[Setup] Creating ${identifiers.length} tags...`);
    let tagPayloads = identifiers.map(identifier => {
        let baseValue = identifier.replace("tagId_", "").replace("roleId_", "");
        let uniqueValue = `${baseValue}_${runSuffix}`; // Append unique suffix safely
        let isUnique = baseValue.startsWith("Clue_") || baseValue.startsWith("Event_") || identifier.startsWith("roleId_");

        return { value: uniqueValue, isUnique: isUnique, expiresAfterMinutes: 0 };
    });

    let tagsRes = http.post(`${BASE_URL}/tags`, JSON.stringify(tagPayloads), { headers: adminHeaders });
    if (tagsRes.status !== 201) throw new Error(`Tag creation failed: ${tagsRes.body}`);

    let createdTags = tagsRes.json();
    let idMap = {};

    identifiers.forEach(identifier => {
        let baseValue = identifier.replace("tagId_", "").replace("roleId_", "");
        let uniqueValue = `${baseValue}_${runSuffix}`;

        // FIXED: Use EXACT match (===), not .startsWith(), to prevent Player1 from matching Player10!
        let tagObj = createdTags.find(t => t.value === uniqueValue);
        if (tagObj) {
            idMap[`{{${identifier}}}`] = tagObj.id; // Map full placeholder -> Tag ID
        } else {
            console.error(`[Setup] Critical Error: Tag not found for value ${uniqueValue}`);
        }
    });

    // 4. Create Roles (with globally unique names)
    console.log(`[Setup] Creating ${USER_COUNT} base roles...`);
    scenarioObj.roles.forEach(role => {
        let placeholder = role.roleId; // e.g., "{{roleId_Player1}}"
        let roleName = placeholder.replace("{{roleId_", "").replace("}}", "");

        let rolePayload = {
            name: `${roleName}_${runSuffix}`, // Globally unique role name
            description: role.descriptionForGM,
            tags: [idMap[placeholder]] // FIXED: Use exact placeholder to get the Tag ID safely
        };

        let roleRes = http.post(`${BASE_URL}/roles`, JSON.stringify(rolePayload), { headers: adminHeaders });
        if (roleRes.status !== 201) throw new Error(`Role creation failed: ${roleRes.body}`);

        // FIXED: Overwrite the Tag ID with the actual Role ID for final scenario replacement!
        idMap[placeholder] = roleRes.json().id;
    });

    // 5. Replace Placeholders & Post Final Scenario
    console.log("[Setup] Posting final Scenario...");
    for (let [placeholder, realId] of Object.entries(idMap)) {
        scenarioStr = scenarioStr.split(placeholder).join(realId);
    }

    let scenarioRes = http.post(`${BASE_URL}/scenarios`, scenarioStr, { headers: adminHeaders });
    if (scenarioRes.status !== 201) throw new Error(`Scenario creation failed: ${scenarioRes.body}`);

    let createdScenario = scenarioRes.json();
    let scenarioId    = createdScenario.id;
    let itemId        = createdScenario.items && createdScenario.items.length > 0 ? createdScenario.items[0].id : null;
    let returnedRoles = createdScenario.roles;

    if (!itemId) throw new Error("Backend did not return any items in the Scenario response!");
    if (!returnedRoles || returnedRoles.length === 0) throw new Error("Backend did not return generated roles in the Scenario response!");

    // 6. Create Event & Assign Users
    console.log("[Setup] Creating Event and assigning users...");
    const assignedRoles = returnedRoles.map((roleObj, index) => ({
        scenarioRoleId: roleObj.id,
        assignedEmail: `user-${index + 1}@loadtest.local`
    }));

    const eventPayload = {
        name: "K6 Automated Loadtest Event",
        description: "K6 Automated Loadtest Event description",
        date: new Date().toISOString(),
        scenarioId: scenarioId,
        assignedRoles: assignedRoles
    };

    let eventRes = http.post(`${BASE_URL}/events`, JSON.stringify(eventPayload), { headers: adminHeaders });
    if (eventRes.status !== 200 && eventRes.status !== 201) throw new Error(`Event creation failed: ${eventRes.body}`);
    
    let eventId = eventRes.json().id;

    // Activate Event (Creates Game Session)
    console.log("[Setup] Activating Event...");
    let activateRes = http.put(`${BASE_URL}/events/${eventId}/status`, JSON.stringify({ status: 'ACTIVE' }), { headers: adminHeaders });
    if (activateRes.status !== 200) throw new Error(`Event activation failed: ${activateRes.body}`);
    
    // Fetch Game & Map Roles (Using Admin Auth)
    console.log("[Setup] Mapping Users to GameSessionRoleIds...");
    let gamesRes = http.get(`${BASE_URL}/game`, { headers: adminHeaders });
    let gamesList = gamesRes.json();
    if (!gamesList || gamesList.length === 0) throw new Error("No active games found!");

    // FIX: Find the exact game we just created instead of grabbing index 0.
    // Adjust the property name ('scenarioId' or 'eventId') based on what your API returns in the Game object.
    let targetGame = gamesList.find(g => g.scenarioId === scenarioId) || gamesList.find(g => g.eventId === eventId);

    // Fallback: If your API doesn't expose scenario/event ID on the game list,
    // grab the last one in the array (often the newest, but less safe than exact matching).
    if (!targetGame) {
        targetGame = gamesList[gamesList.length - 1];
    }

    let gameId = targetGame.id;
    if (!gameId) throw new Error("Extracted Game ID is undefined/null!");

    let mappedUsers =[];
    for (let i = 1; i <= USER_COUNT; i++) {
        let uid = `user-${i}`;
        let roleStateRes = http.get(`${BASE_URL}/game/${gameId}/role/user/${uid}`, { headers: adminHeaders });
        
        if (roleStateRes.status !== 200) {
            throw new Error(`Failed to map user ${uid}. Response: ${roleStateRes.body}`);
        }

        let roleStateData = roleStateRes.json();
        
        // Find the scenario role ID from the assignment we created
        let userAssignment = assignedRoles.find(ar => ar.assignedEmail === `${uid}@loadtest.local`);
        let scenarioRoleId = userAssignment ? userAssignment.scenarioRoleId : null;

        mappedUsers.push({
            userId: uid,
            token: uid,
            gameSessionRoleId: roleStateData.gameSessionRoleId || roleStateData.id,
            scenarioRoleId: scenarioRoleId
        });
    }

    console.log(`--- Setup Complete --- \nGameId: ${gameId}\nItemId: ${itemId}\nUsers Mapped: ${mappedUsers.length}`);
    return { gameId: gameId, itemId: itemId, users: mappedUsers };
}

export default function (data) {
    const userIndex = (exec.vu.idInTest - 1) % USER_COUNT;
    const user = data.users[userIndex];
    
    const reqOptions = {
        headers: {
            'Authorization': `Bearer ${user.token}`,
            'Content-Type': 'application/json'
        }
    };

    console.log(`[VU-${exec.vu.idInTest}] Executing as User: ${user.userId} | GameSessionRoleID: ${user.gameSessionRoleId} | ScenarioRoleID: ${user.scenarioRoleId}`);

    // Step 1: Load Full Game State as assigned user
    let gameStateRes = http.get(`${BASE_URL}/game/${data.gameId}`, reqOptions);
    check(gameStateRes, { '[S1] Game State 200': (r) => r.status === 200 });
    sleep(Math.random() * 2 + 1);

    // Step 2: Get Available Global Actions
    let availActionsRes = http.get(`${BASE_URL}/game/roles/${user.gameSessionRoleId}/availableActions`, reqOptions);
    check(availActionsRes, { '[S2] Global Actions 200': (r) => r.status === 200 });
    sleep(1);

    // Step 3: Scan Item Actions
    let itemActionsRes = http.get(`${BASE_URL}/game/roles/${user.gameSessionRoleId}/items/${data.itemId}/availableActions`, reqOptions);

    if (itemActionsRes.status !== 200) {
        console.error(`[VU-${exec.vu.idInTest}] Step 3 Failed! Status: ${itemActionsRes.status}, Body: ${itemActionsRes.body}`);
    }
    check(itemActionsRes, { '[S3] Item Actions 200': (r) => r.status === 200 });
    
    let actionsToExecute = itemActionsRes.status === 200 ? itemActionsRes.json() :[];
    sleep(1.5);

    // Step 4: Perform Action
    if (actionsToExecute.length > 0) {
        let actionId = actionsToExecute[0].id; 
        
        let performActionPayload = JSON.stringify({
            performerRoleId: user.scenarioRoleId,
            actionId: actionId,
            targetItemId: data.itemId
        });

        let execRes = http.post(`${BASE_URL}/game/${data.gameId}/perform-action`, performActionPayload, reqOptions);
        check(execRes, { '[S4] Action executed': (r) => [200, 201].includes(r.status) });
    }
    sleep(1);

    // Step 5: Refetch Available Actions
    let updatedActionsRes = http.get(`${BASE_URL}/game/roles/${user.gameSessionRoleId}/availableActions`, reqOptions);
    check(updatedActionsRes, { '[S5] State refetched 200': (r) => r.status === 200 });
    sleep(0.5);

    // Step 6: Fetch Action History
    let historyRes = http.get(`${BASE_URL}/game/history/user/gameId/${data.gameId}`, reqOptions);
    check(historyRes, { '[S6] History fetched 200': (r) => r.status === 200 });

    // End of loop cycle
    sleep(Math.random() * 3 + 2); 
}

export function handleSummary(data) {
    return {
        "summary.html": htmlReport(data),
    };
}
