spring.config.import=classpath:env/.env[.properties]
  
  # Neon Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
  
  # Logger Configuration
logging.level.com.larplaner=debug
  
  # Firebase config file
firebase.service-account.path=${FIREBASE_SVC_ACCOUNT_PATH}
  
  # --- Local HTTPS Configuration ---
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:config/keystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
